
;-----------------------------------------------------------------------------
;				LIB_SYS.ASH
;-----------------------------------------------------------------------------

		extrn	SYSCALL	TimerRef:DWORD
		extrn	SYSCALL	NbFramePerSecond:WORD
		extrn	SYSCALL	WaitNbTicks:WORD
		extrn	SYSCALL	CmptFrame:WORD
		extrn	SYSCALL	Cmpt_18:WORD

;TIMERREF		equ	0
;NBFRAMEPERSECOND      	equ	4
;WAITNBTICKS		equ	6
;CMPTFRAME		equ	8
;CMPT_18		equ	10

;-----------------------------------------------------------------------------





